### ISSUE TITLE
Blog Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#193]
Please share a screenshot with an elaborate description of what part you want to improve on or any bug you wish to fix

**Comment by Satyam3976** [comment]
Can I work on this

**Comment by shwetagurnani** [comment]
Please assign me this issue:)

**Comment by aashimgarg** [comment]
overflow property should be used for the content.

![Screenshot from 2020-04-06 16-57-10](https://user-images.githubusercontent.com/55639487/78554060-0ec46b80-7828-11ea-9acb-179ca6b5dace.png)

Excess margin on both the sides on the blog posts.

![Screenshot from 2020-04-06 16-57-28](https://user-images.githubusercontent.com/55639487/78554161-4501eb00-7828-11ea-8048-21f0ab5f4768.png)

Hey @smaranjitghose i want too work on this issue.

**Comment by ashishnagpal2498** [comment]
Cleaning -  Removing 
1) Inline CSS
2) Deprecated tags like font, center etc.

**Comment by goyalmuskan** [comment]
Sir, may I work on this issue? @smaranjitghose

**Comment by goyalmuskan** [comment]
@smaranjitghose Can I still work on this? I need to link social media icons and improve the first section.

**Comment by smaranjitghose** [comment]
Ya sure

**Comment by abhu-A-J** [comment]
@smaranjitghose Sir, it has the following issues:
- Navbar is inconsistent
- The styling of heading, subheads etc is completely off from another page
-  The section is filled with inline styles and I would like to clean that out because it will create specificity issues! 
- Also I can make the header look a little than it is right now.

May I move forward if you feel they are important to address?

![Screenshot (102)](https://user-images.githubusercontent.com/49617450/78862278-9e4e6200-7a54-11ea-9867-d6d1c3cfbf5f.png)
![Screenshot (103)](https://user-images.githubusercontent.com/49617450/78862283-a0182580-7a54-11ea-81ef-7c154cca982f.png)

**Comment by anushbhatia** [comment]
Sure move ahead!

**Comment by abhu-A-J** [comment]
> Sure move ahead!

Thank you! :)
