### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#194]
Please share a screenshot with an elaborate description of what part you want to improve on or any bug you wish to fix

**Comment by shwetagurnani** [comment]
Can I work on it?

**Comment by Satyam3976** [comment]
I can Work on this, please issue me this

**Comment by abhu-A-J** [comment]
@smaranjitghose Sir, I want to work on this: 
Currently the flipping card animations look great on the homepage but it is a **UX bug** for devices on which we  **can't hover** there is no way for user to know if content exists behind the card until the click on this ( since hover converts to click on such devices)
I want to write **advanced media queries** to judge if a device is **(touch based or supports hover or not) and render these components differently on different devices**!!!

On devices on which there is no hover I'll bring the backside of the side to the bottom , so they appear as a single card !!!  

@smaranjitghose Sir, Do you think it's needed . If yes, I'd like to this is challenge!

**Comment by ashishnagpal2498** [comment]
Cleaning -  Removing 
1) Inline CSS from homepage
2) Deprecated tags like font, center etc.

**Comment by smaranjitghose** [comment]
@ashishnagpal2498 Please be more specific with some Screenshots

**Comment by ashishnagpal2498** [comment]
@smaranjitghose , use of font as tag. using inline CSS like here -
![image](https://user-images.githubusercontent.com/36301481/78559092-661b0980-7831-11ea-845c-ff7da7642688.png)

**Comment by raniyer** [comment]
<b>Hi, I would like to work on these issues on the home/index page.</b>

1) Add animation to the image slider behind "welcome to GirlsScript Chennai"
![Capture](https://user-images.githubusercontent.com/46458711/78748965-de491280-798a-11ea-8dd2-8b49f3a36090.PNG)

2) rectify the flipped card error. See image.
![fliperror](https://user-images.githubusercontent.com/46458711/78748962-ddb07c00-798a-11ea-9fbe-cc8bb959b13f.PNG)

3) remove the extra space
![emptyspace](https://user-images.githubusercontent.com/46458711/78748908-c5d8f800-798a-11ea-8e2a-d83b5349984d.PNG)

4) add subheading to the following icons:
![addsubheading](https://user-images.githubusercontent.com/46458711/78748973-e2753000-798a-11ea-8135-96fdf3e9d3ab.PNG)

**Comment by smaranjitghose** [comment]
Sure, go ahead with the changes

**Comment by anushbhatia** [comment]
Can someone make the home carousel more smoother as it takes really long time to load?
either use optimized images or use a different code for carousel.

**Comment by abhu-A-J** [comment]
> Can someone make the home carousel more smoother as it takes really long time to load?
> either use optimized images or use a different code for carousel.

@anushbhatia  Sir may I do this?

**Comment by smaranjitghose** [comment]
@abhu-A-J  coordinate with @raniyer on this issue then so that there are no merge conflicts

**Comment by shreyakapoor08** [comment]
@smaranjitghose Email id validation required for the input field in the footer.
Can I work on this ?

**Comment by smaranjitghose** [comment]
Ya, please improve on those Shreya
