### ISSUE TITLE
:feat: scrollToTop  => ( using vanillaJS )

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#583]
**Description of the enhancement**
I think its a better alternative rather than importing the jQuery library for this function.

**Comment by Muskan-Mangal** [comment]
@aashimgarg  you still have to import jquery since it's used in many script in the project.
I am improving the performance by removing the slim calls instead of minified calls though since slim lacks AJAX calls and animations etc but minified include all this. Other than that it improves the speed, consume less data and less battery charge too.

**Comment by aashimgarg** [comment]
I am working on it.

**Comment by Muskan-Mangal** [comment]
okay so can you explain why vanilla?

**Comment by Muskan-Mangal** [comment]
I am just trying to tell you that jquery hasn't been imported only for that scroll to top function.
Even if you solve this by vanilla u have to load that still so why are you redoing a thing.
Lets have suggestions from or mentors.
@smaranjitghose  @anushbhatia 
Please suggest what we should we with. I am agree with any of them since performance and efficiency is the priority.

**Comment by smaranjitghose** [comment]
Yes @Muskan-Mangal is right about this. We are anyways using jquery for other sections
